
BookCategory.create!(name: 'Choose category...')
BookCategory.create!(name: 'Action and Adventure')
BookCategory.create!(name: 'Classics')
BookCategory.create!(name: 'Comic Book or Graphic Novel')
BookCategory.create!(name: 'Detective and Mystery')
BookCategory.create!(name: 'Fantasy')
BookCategory.create!(name: 'Historical Fiction')
BookCategory.create!(name: 'Horror')
BookCategory.create!(name: 'Literary Fiction')
BookCategory.create!(name: 'Romance')
BookCategory.create!(name: 'Science Fiction (Sci-Fi)')
BookCategory.create!(name: 'Short Stories')
BookCategory.create!(name: 'Suspense and Thrillers')
